# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e85ea145526c289dcf5204174aebc0c0a94d8c8d63f8046392a07973585b788d6d70b45ff7eafb7ad7767c4da4e13af43a9ced30ed495d89b655b969ab10d4ba

test:
  secret_key_base: a55d6a98242bc006bef5a412e03c0d81bd70944f58a49c3e7d468e8e326a2715e93fa69a1b9240f2ceb672b7a4c5d4263f990c9fd88bf14fe95a4cc5c487d8bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
